name: Build and Upload Workflow

on:
  push:
    branches:
      - master
    # Run only if the commit message contains "release"
    tags:
      - '*'

jobs:
  build-and-upload:
    if: contains(github.event.head_commit.message, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build for production
        run: npx mix --production

      - name: Extract Stable Tag from readme.txt
        id: extract_tag
        run: |
          # Extract the stable tag value from readme.txt
          STABLE_TAG=$(grep -E '^Stable tag:' readme.txt | awk -F ': ' '{print $2}')
          echo "STABLE_TAG=$STABLE_TAG" >> $GITHUB_ENV

      - name: Prepare zip file
        run: |
          mkdir fluent-smtp-indiv
          rsync -aq --exclude=fluent-smtp-indiv --exclude=.git --exclude=.github --progress ./ ./fluent-smtp-indiv
          zip -r fluent-smtp-indiv.zip ./fluent-smtp-indiv

      - name: Upload to wp-api.indiv.nl
        env:
          API_KEY: ${{ secrets.API_KEY }}
          STABLE_TAG: ${{ env.STABLE_TAG }}
        run: |
          curl \
            -F "file=@the-plugin-name.zip" \
          -F "stable_tag=${STABLE_TAG}" \
          -F "api_key=${API_KEY}" \
            https://wp-api.indiv.nl/plugins/smtp/release.php